# Generated by Django 3.2.12 on 2023-04-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
