# Generated by Django 3.2.12 on 2023-04-17 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novadata_utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_delete_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('novadatamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='novadata_utils.novadatamodel')),
                ('mensagem', models.CharField(max_length=100, verbose_name='Mensagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificação',
            },
            bases=('novadata_utils.novadatamodel',),
        ),
    ]
