# Generated by Django 3.2.12 on 2023-04-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
    ]
