# Generated by Django 3.2.12 on 2023-05-06 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novadata_utils', '0001_initial'),
        ('servicos', '0002_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('novadatamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='novadata_utils.novadatamodel')),
                ('tipo', models.CharField(choices=[('Manutenção', 'Manutenção'), ('Instalação', 'Instalação'), ('Proposta', 'Proposta'), ('Chamado', 'Chamado')], max_length=100, verbose_name='Tipo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.cliente', verbose_name='Cliente')),
                ('functionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
            bases=('novadata_utils.novadatamodel',),
        ),
    ]
