# Generated by Django 3.2.12 on 2023-05-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_visita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='functionario',
            new_name='funcionario',
        ),
    ]
