# Generated by Django 3.2.12 on 2023-05-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_estacaosolar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstacaoSolar',
        ),
    ]
