# Generated by Django 3.2.12 on 2023-05-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0009_remove_estacaosolar_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='realizada',
            field=models.BooleanField(default=False, verbose_name='Realizada'),
        ),
    ]
