# Generated by Django 3.2.12 on 2023-05-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0011_auto_20230516_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacaosolar',
            name='consumo_mensal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo mensal (kW/h)'),
        ),
        migrations.AlterField(
            model_name='estacaosolar',
            name='geracao_mensal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Geração mensal por placa (kW/h)'),
        ),
        migrations.AlterField(
            model_name='estacaosolar',
            name='kw_placa',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='(kW/h) da placa'),
        ),
    ]
